apiVersion: v1
kind: Service
metadata:
  name: api-naming-intern-project-service-parri
  namespace: parri-development
spec:
  type: LoadBalancer
  selector:
    app: api-naming-intern-project-parri
  ports:
    - name: http
      port: 4040
      targetPort: 4040
